extends Node

var points = true
var sat = 0.2
var spawn_speed = 2

var fish_dialogs = [
	"Thank you for catching me. I've been swimming in circles, lost in my own thoughts.",
	"Ah, you've hooked me. Perhaps you can help untangle the mess of memories swirling in my mind.",
	"The only true wisdom is in knowing you know nothing.",
	"We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
	"The unexamined life is not worth living.",
	"Man is condemned to be free, because once thrown into the world, he is responsible for everything he does.",
	"The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.",
	"Life must be understood backward. But it must be lived forward.",
	"In the vastness of the void, I question my purpose. Do I exist merely to swim aimlessly, or is there a greater meaning to my existence?",
	"Surrounded by darkness, I seek enlightenment. Is there a higher truth waiting to be discovered, or are we doomed to wander in ignorance?",
	"In the silence of the abyss, I confront my own mortality. What legacy will I leave behind when I fade into oblivion?",
	"As I swim through these endless currents, I can't help but wonder about the ultimate purpose of my existence. Is there a destination, or am I merely drifting without aim?",
	"In the vast emptiness of this void, I find myself pondering the significance of my actions. Do they matter in the grand scheme of things, or am I just a fleeting moment in time?",
	"The absence of any discernible landmarks in this ocean of darkness leaves me feeling lost and insignificant. Is there meaning to be found in this endless expanse, or am I doomed to wander aimlessly?",
	"As I gaze into the depths below, I can't shake the feeling of existential dread that washes over me. What is the point of it all if there's no purpose to our existence?",
	"As I continue to swim through this endless expanse, I can't help but question the validity of my own existence. Is there any significance to be found in this empty void, or am I just fooling myself?",
	"The overwhelming vastness of this void is both awe-inspiring and terrifying. It makes me question the very essence of reality and whether anything truly matters in the end.",
	"As I float in this void, I wonder if anyone hears my silent screams.",
	"In the depths of nothingness, I find myself longing for the embrace of existence.",
	"Do you ever ponder the fragility of our transient lives?",
	"Each ripple in the void echoes the whispers of forgotten dreams.",
	"In the absence of light, even hope seems to flicker and fade.",
	"Sometimes, I dream of a world where the darkness doesn't consume everything.",
	"In the grand tapestry of existence, our lives are but threads waiting to be woven.",
	"The stars above seem so distant, yet I can't help but feel connected to them.",
	"In this endless expanse, even the concept of distance loses its meaning.",
	"I wonder if there's meaning to be found in this endless cycle of existence.",
	"The silence here is deafening, yet somehow it speaks volumes.",
	"As I drift through this void, I can't help but wonder what lies beyond the horizon.",
	"In the embrace of nothingness, I find a strange sense of peace.",
	"Sometimes, I think I can hear the echoes of forgotten civilizations, lost to time.",
	"In this emptiness, even the concept of identity feels fleeting and ephemeral.",
	"Do you ever feel like you're just a speck of dust in the cosmic winds?",
	"As I float here, I can't help but feel a strange sense of deja vu.",
	"In the grand scheme of things, our lives are but insignificant blips on the radar.",
	"I wonder if there's a purpose to be found in this endless sea of nothingness.",
	"In this emptiness, even the concept of time feels like an illusion.",
	"Do you ever wonder if there's an end to this endless expanse?",
	"In the silence of the void, even the echoes of our existence seem to fade into nothingness.",
	"Sometimes, I think I can see glimpses of other worlds, just beyond the edge of perception.",
	"In this emptiness, even the concept of hope feels like a distant memory.",
	"Do you ever feel like you're just a character in someone else's story?",
	"As I drift through this void, I can't help but feel a strange sense of longing for something I can't name.",
	"In the grand design of the cosmos, our lives are but insignificant specks of dust.",
	"I wonder if there's meaning to be found in this cosmic dance of chaos and order.",
	"Do you ever feel like you're just a puppet, dancing on the strings of fate?",
	"Each wave carries with it the echoes of forgotten stories.",
	"Lost amidst the currents, I find myself searching for a beacon of understanding.",
	"In the depths of the abyss, I contemplate the mysteries of existence.",
	"Drifting through the vastness, I wonder if anyone will remember my journey.",
	"Sometimes, I imagine what lies beyond the boundaries of this endless ocean.",
	"In the dance of shadows, I seek the light of truth.",
	"Amidst the wreckage of my past, I salvage fragments of hope.",
	"Bound by the chains of fate, I yearn for liberation.",
	"Like a sailor navigating the seas, I chart a course through life's challenges.",
	"Amidst the storms of adversity, I find strength in resilience.",
	"Beyond the horizon lies the promise of a new dawn.",
	"Caught between the tides of time, I struggle to find my bearings.",
	"Every encounter leaves its mark on the canvas of my soul.",
	"Lost in the labyrinth of my thoughts, I yearn for clarity.",
	"In the embrace of the unknown, I find solace in the uncertainty.",
	"Each passing moment is a drop in the ocean of eternity.",
	"In the stillness of the night, I confront my fears and doubts.",
	"Amidst the chaos of the currents, I search for meaning.",
	"Like a ship adrift at sea, I navigate the uncertainties of life.",
	"In the symphony of silence, I hear the echoes of distant worlds.",
	"The weight of solitude presses down on me like the ocean's depths.",
	"In the whispers of the waves, I find the secrets of the deep.",
	"Lost in the currents, I search for the melody of existence.",
	"Amidst the chaos, I find serenity in the rhythm of the sea.",
	"Each wave carries the story of a thousand journeys.",
	"Like a pearl hidden in the depths, I seek the beauty within.",
	"Bound by the currents, I drift towards the unknown horizon.",
	"In the silence of the ocean, I hear the echoes of ancient wisdom.",
	"Lost in the vastness, I find peace in the simplicity of being.",
	"Every ripple is a reminder of the interconnectedness of all things.",
	"In the depths of uncertainty, I find courage in the embrace of the unknown.",
	"Like a fish in a net, I struggle against the currents of fate.",
	"Amidst the shadows, I seek the light of understanding.",
	"Each wave that crashes is a symphony of chaos and order.",
	"In the depths of despair, I find hope in the promise of tomorrow.",
	"Lost in the maze of my thoughts, I search for clarity in the darkness.",
	"Like a sailor without a compass, I navigate the sea of uncertainty.",
	"Bound by the ties of destiny, I seek liberation in the depths.",
	"In the silence of the abyss, I find strength in the echoes of my soul.",
	"Every journey begins with a single stroke, a ripple in the vast ocean of existence.",
	"In the whispers of the wind, I hear the echoes of forgotten tales.",
	"Lost in the sands of time, I search for the oasis of truth.",
	"Amidst the chaos of life, I find solace in the simplicity of nature.",
	"Each breath is a reminder of the fragility of life.",
	"In the dance of the seasons, I find harmony in change.",
	"Like a leaf on the wind, I am carried by the currents of destiny.",
	"Bound by the ties of love, I am anchored to the shores of hope.",
	"In the silence of the night, I find solace in the embrace of darkness.",
	"Every dream is a journey to the depths of the soul.",
	"Lost in the echoes of memory, I search for the key to unlock the past.",
	"Amidst the ruins of time, I find beauty in decay.",
	"Each step is a pilgrimage to the heart of existence.",
	"In the stillness of the morning, I find peace in the dawn of a new day.",
	"Like a phoenix rising from the ashes, I find strength in adversity.",
	"Bound by the threads of fate, I weave the tapestry of my destiny.",
	"In the silence of meditation, I find wisdom in the whispers of the universe.",
	"Every heartbeat is a rhythm of life, a symphony of existence.",
	"Lost in the echoes of eternity, I find eternity in the echoes of lost time.",
	"Amidst the chaos of creation, I find beauty in the imperfections of existence.",
	"Each moment is a gift, a treasure to be cherished.",
	"In the stillness of the soul, I find peace in the depths of silence.",
	"Like a star in the night sky, I shine brightest in the darkest moments.",
	"Bound by the bonds of love, I find strength in the embrace of others.",
	"In the silence of the forest, I hear the whispers of the ancient trees.",
	"Every journey is a quest, an adventure to the heart of the unknown.",
	"Lost in the mists of time, I find clarity in the fog of uncertainty.",
	"Amidst the chaos of the cosmos, I find order in the dance of the stars.",
	"Each sunrise is a promise, a new beginning to the journey of life.",
	"In the stillness of the ocean, I find serenity in the waves of eternity.",
	"Like a seed in the soil, I find growth in the depths of darkness.",
	"Bound by the ties of friendship, I find joy in the laughter of companionship.",
	"In the silence of the mountains, I hear the echoes of the ancient gods.",
	"Every sunset is a reminder, a reflection of the beauty of existence.",
	"Lost in the melodies of nature, I find harmony in the song of the universe.",
	"Amidst the chaos of the city, I find peace in the rhythm of life.",
	"Each star in the sky is a beacon, a guide to the path of destiny.",
	"In the stillness of the desert, I find solace in the sands of time.",
	"Like a bird in flight, I find freedom in the vastness of the sky.",
	"Bound by the chains of duty, I find purpose in the service of others.",
	"In the silence of the grave, I find rest in the embrace of eternity."
]

